accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from accounts.views import (
    SignUp,
)

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", SignUp, name="signup"),
]

projects/urls.py
from django.urls import path
from projects.views import (
    ProjectListView,
    ProjectDetailView,
    ProjectCreateView,
)

urlpatterns = [
    path("", ProjectListView.as_view(), name="list_projects"),
    path("<int:pk>/", ProjectDetailView.as_view(), name="show_project"),
    path("create/", ProjectCreateView.as_view(), name="create_project"),
]

tasks/urls.py
from django.urls import path
from tasks.views import TaskCreateView, TaskListView, CompleteTaskUpdateView

urlpatterns = [
    path("create/", TaskCreateView.as_view(), name="create_task"),
    path("mine/", TaskListView.as_view(), name="show_my_tasks"),
    path(
        "<int:pk>/complete/",
        CompleteTaskUpdateView.as_view(),
        name="complete_task",
    ),
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("projects/", include("projects.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("list_projects")),
        name="home",
    ),
    path("accounts/", include("accounts.urls")),
    path("tasks/", include("tasks.urls")),
]

accounts/models.py
# from django.db import models

# Create your models here.

projects/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(default="")
    members = models.ManyToManyField(User, related_name="projects")

    def __str__(self):
        return self.name

tasks/models.py
from django.db import models
from django.contrib.auth.models import User
from projects.models import Project

# Create your models here.


class Task(models.Model):
    name = models.CharField(max_length=200)
    start_date = models.DateTimeField()
    due_date = models.DateTimeField()
    is_completed = models.BooleanField(default=False)
    project = models.ForeignKey(
        Project, related_name="tasks", on_delete=models.CASCADE
    )
    assignee = models.ForeignKey(
        User, related_name="tasks", on_delete=models.SET_NULL, null=True
    )

    def __str__(self):
        return self.name

accounts/views.py
from django.contrib.auth import login
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect

# Create your views here.


def SignUp(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)  # make instance of UserCform
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password1")
            user = User.objects.create(
                username=username,
                password=password,
            )
            user.save()  # save our new instance of a user
            login(request, user)  # login our new user
            return redirect("home")  # redirect that user home after login
    else:
        form = UserCreationForm()
    context = {
        "form": form,
    }
    return render(request, "registration/signup.html", context)

projects/views.py
from django.shortcuts import redirect
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView
from projects.models import Project
from django.contrib.auth.mixins import LoginRequiredMixin


class ProjectListView(LoginRequiredMixin, ListView):
    model = Project
    template_name = "projects/list.html"

    def get_queryset(self):
        return Project.objects.filter(members=self.request.user)


class ProjectDetailView(LoginRequiredMixin, DetailView):
    model = Project
    template_name = "projects/detail.html"

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    # #context_userproject = Project.objects.filter(members=self.request.user)
    #    context["userproject"] = context_userproject
    #     return context


class ProjectCreateView(LoginRequiredMixin, CreateView):
    model = Project
    template_name = "projects/new.html"
    fields = ["name", "description", "members"]

    def form_valid(self, form):
        returnedQuerySet = form.cleaned_data.get("members")
        name = form.cleaned_data.get("name")
        description = form.cleaned_data.get("description")
        newproject = Project.objects.create(name=name, description=description)
        for member in returnedQuerySet.iterator():
            newproject.members.add(member)
            return redirect("show_project", pk=newproject.id)

tasks/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView
from tasks.models import Task
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.


class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    template_name = "tasks/new.html"
    fields = ["name", "start_date", "due_date", "project", "assignee"]

    def form_valid(self, form):
        form.instance.tasks = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("show_project", args=[self.object.id])


class TaskListView(LoginRequiredMixin, ListView):
    model = Task
    template_name = "tasks/list.html"

    def get_queryset(self):
        # filter out to see only the assignee potss
        return Task.objects.filter(assignee=self.request.user)


class CompleteTaskUpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    template_name = "tasks/new.html"
    fields = ["is_completed"]

    def get_success_url(self):
        return reverse_lazy("show_my_tasks")

projects/templates/projects/detail.html
{% extends 'projects/navbar.html' %}
{% load markdownify %}
{% block content %}
    <main>
        <div>
            <h1>{{project.name}}</h1>
            <p>{{project.description|markdownify}}</p>
            <h2>Tasks</h2>
            <p><a href="{% url 'create_task' %}">Create a new task</a></p>
            {% if project.tasks.all|length > 0 %}
                <table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Assignee</th>
                            <th>Start date</th>
                            <th>Due date</th>
                            <th>Is completed</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for task in project.tasks.all %}
                            <tr>
                                <td>
                                    {{task}}
                                </td>
                                <td>
                                    {{task.assignee}}
                                </td>
                                <td>
                                    {{task.start_date}}
                                </td>
                                <td>
                                    {{task.due_date}}
                                </td>
                                {% if task.is_completed == True %}
                                    <td>yes</td>
                                {% else %}
                                    <td> no </td>
                                {% endif %}
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>This project has no tasks</p>
            {% endif %}
        </div>
    </main>
{% endblock content %}

projects/templates/projects/list.html
{% extends 'projects/navbar.html' %}

{% block content %}
    <main>
        <div>
            <h1>My Projects</h1>
            <p><a href="{% url 'create_project'%}">Create a new project</a></p>

            {% if project_list|length == 0 %}
                <p>You are not assigned to any projects</p>
            {% else %}
                <table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Number of tasks</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for proj in project_list %}
                            <tr>
                                <td><a href="{% url 'show_project' proj.pk %}">{{proj.name}}</a></td>
                                <td>{{proj.tasks.all|length}}</td>
                            </tr>
                            </tbody>
                        {% endfor %}
                    </table>
            {% endif %}
        </div>
    </main>
{% endblock content %}

projects/templates/projects/navbar.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                        <li>
                            <a href="{% url 'show_my_tasks' %}">My tasks</a>
                        </li>
                        <li>
                            <a href="{% url 'list_projects' %}">My projects</a>
                        </li>
                        <li>
                            <a href="{% url 'logout' %}">Logout</a>
                        </li>
                    {% else %}
                        <li>
                            <a href="{% url 'login' %}">Login</a>
                        </li>
                        <li>
                            <a href="{% url 'signup' %}">Signup</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        {% block content %}
        {% endblock content %}
    </body>
</html>

projects/templates/projects/new.html
{% extends 'projects/navbar.html' %}

{% block content %}
    <main>
        <div>
            <h1>Create a new project</h1>
            <form method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button>Create</button>
            </form>
        </div>
    </main>

{% endblock content %}

tasks/templates/tasks/list.html
{% extends 'projects/navbar.html' %}

{% block content %}
    <main>
        <div>
            <h1>My Tasks</h1>
            {% if task_list|length > 0 %}
                <table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Start date</th>
                            <th>End date</th>
                            <th>Is completed</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for category in task_list %}
                            <tr>
                                <td>{{category.name}}</td>
                                <td>{{category.start_date|date:"M d, Y"}}</td>
                                <td>{{category.due_date|date:"M d, Y"}}</td>
                                <td>
                                    {% if category.is_completed %}
                                        <p>Done</p>
                                    {% else %}
                                        <form method="post" action="{% url 'complete_task' category.id %}">
                                            {% csrf_token %}
                                            <input type="hidden" name="is_completed" value="True">
                                            <button>Complete</button>
                                        </form>
                                    {% endif %}
                                </td>
                            </tr>
                            </tbody>
                        {% endfor %}
                    </table>

            {% else %}
                <p>You have no tasks</p>

            {% endif %}
        </div>
    </main>
{% endblock content %}

tasks/templates/tasks/new.html
{% extends 'projects/navbar.html' %}

{% block content %}
    <main>
        <div>
            <h1>Create a new task</h1>
            <form method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button>Create</button>
            </form>
        </div>
    </main>
{% endblock content %}